# Generated by Django 4.2.7 on 2023-11-01 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Perritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePerrito', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Propietarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('edad', models.IntegerField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreraza', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=100)),
                ('edad', models.IntegerField(max_length=2)),
                ('nombrePerrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_perritos', to='perritos.perritos')),
            ],
        ),
        migrations.AddField(
            model_name='perritos',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_Propietarios', to='perritos.propietarios'),
        ),
    ]
